// Trial answers from audition/judge.html (D52, patterns added D54).
//
// GENERATED by scripts/import-verdicts.mjs — do not hand-edit.
//
// Each key is a trial id; `asks` is the question that trial was built to
// settle, and `a`/`b` name which ARM each side came from, so a tally over
// these answers is a controlled comparison rather than a vibe.
//
// `pattern` is the interval pattern that was SOUNDING when the answer was
// given and `heard` is every pattern auditioned on that trial (D54). A
// preference that flips between block chords and an arpeggio is a finding
// about texture; one that holds across six is a finding about harmony.

export const JUDGMENTS = {
  "t0": {
    "type": "ab",
    "value": "neither",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "generated",
    "b": "varied"
  },
  "t1": {
    "type": "ab",
    "value": "same",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "varied",
    "b": "generated"
  },
  "t2": {
    "type": "ab",
    "value": "B",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "varied",
    "b": "generated"
  },
  "t3": {
    "type": "ab",
    "value": "B",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "generated",
    "b": "varied"
  },
  "t4": {
    "type": "ab",
    "value": "neither",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "varied",
    "b": "generated"
  },
  "t5": {
    "type": "ab",
    "value": "B",
    "asks": "D50 exemplar variation vs D49 statistical composition",
    "a": "varied",
    "b": "generated"
  },
  "t6": {
    "type": "ab",
    "value": "neither",
    "asks": "does a typed substitution help or hurt",
    "a": "foundation",
    "b": "varied"
  },
  "t7": {
    "type": "ab",
    "value": "B",
    "asks": "does a typed substitution help or hurt",
    "a": "varied",
    "b": "foundation"
  },
  "t8": {
    "type": "ab",
    "value": "same",
    "asks": "does a typed substitution help or hurt",
    "a": "varied",
    "b": "foundation"
  },
  "t9": {
    "type": "ab",
    "value": "same",
    "asks": "does a typed substitution help or hurt",
    "a": "foundation",
    "b": "varied"
  },
  "t10": {
    "type": "ab",
    "value": "A",
    "asks": "does a typed substitution help or hurt",
    "a": "foundation",
    "b": "varied"
  },
  "t11": {
    "type": "ab",
    "value": "neither",
    "asks": "does a typed substitution help or hurt",
    "a": "varied",
    "b": "foundation"
  },
  "t12": {
    "type": "ab",
    "value": "neither",
    "asks": "does a typed substitution help or hurt",
    "a": "varied",
    "b": "foundation"
  },
  "t13": {
    "type": "ab",
    "value": "neither",
    "asks": "does a typed substitution help or hurt",
    "a": "foundation",
    "b": "varied"
  },
  "t14": {
    "type": "ab",
    "value": "B",
    "asks": "is composed harmony competitive with the imported pool",
    "a": "generated",
    "b": "corpus"
  }
};

// Notes typed on trials that were never answered — a sentence is worth more
// than the verdict it came with, so skipping past one does not discard it.
export const STRAY_NOTES = {
  "t15": "I like B - wide pad, arpeggio, wide arp, oom pan, roots only are classics",
  "t16": "B sounds hopeful (widpad)",
  "t19": "I like B but Cm to Cm7 3 times thrown in with one G7 rhythm-wise and pattern-wise progresses weird. why not just Cm Cm7 Cm G7 or something like that?",
  "t20": "I like A wide pad - sounds regretful or \"aftermath of a disaster\". could vary the last chord -> change Cm to another chord. \n\nlove the Gm to G as an ending pair",
  "t21": "in A, the fourth G could be changed to something else as a variation (it's fine as it is but could be replaced eventually in the song so it's not uniform)",
  "t22": "wide pad is fine but I feel like this pattern isn't meant to be jamming the full chord each time. maybe like oom-pah but keeping the wide pad's notes of the actual chord progression",
  "t23": "I think the last Cm should be replaced with something else (like maybe G major chord or something of that nature) because the double Cm back to back doesn't sound too good",
  "t26": "five chords - sounds awkward in timing but the chords work. im thinking Cm Db7 Cm Ab7 as one chord progression then Fm7 as the beginning of another chord progression like Cm Db7 Cm Ab7 Fm7 [x] Fm7 [x]",
  "t27": "fourth Cm should be replaced with something else - back to back Cm is ok sometimes but sounds uniform",
  "t28": "good for 3/4 but timings should be aligned for 4/4 or other time signatures. \n\nit could also sometimes eventually in the song go up more. like B chord, Db chord, up another interval chord, up another interval chord as kinda like hope",
  "t29": "I like the descending pattern",
  "t30": "Gsus followed by Dsus is a bit strange. moreover another G added to the end is strange because it makes it 5 chords and it's back to back G",
  "t31": "hopeful - I like",
  "t32": "already said this"
};
