// Ear verdicts (D51): what Ethan kept and what he killed, per library entry.
//
// GENERATED by scripts/import-verdicts.mjs from an audition page's exported
// JSON — do not hand-edit; re-run the importer with a fresh export.
//
// This is the ONLY quality signal the project has. Everything else in the
// corpus records what a progression IS, never whether it is any good. A6.1
// says a character line is earned by ear and never generated at import; this
// file is where that ear is written down.
//
// `kill` entries are kept deliberately. Negative evidence is scarcer than
// positive here and at least as useful for ranking.
//
// CAVEAT ON WHAT A VERDICT MEANS. These came from audition/undertale.html,
// which plays a FULL ARRANGEMENT — so a verdict mixes the harmony with the
// instruments, the form and the mix. It is a judgment on the card, not
// cleanly on the progression. See D51 for what the verdicts turned out to
// correlate with.

export const VERDICTS = {
  ut_alphys_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "10 0:7 10 0:7 10 0:7 10 0:7" },
  ut_alphys_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "10 0:7 2:m7 10 0:7 2:m7 10 0:7 2:m7 10 0:7 2:m7" },
  ut_alphys_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "10 5:^7 2:m 5:^7 7" },
  ut_amalgam_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "8 6 3:m 1 3 4 11 8:m 3:7 6 4" },
  ut_amalgam_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "3:m 10:m 0:m 10:m" },
  ut_burn_in_despair_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "1:^7 7:6 11:sus 8:m 0:m 8:m 0:m 2:m 8:6 0:sus 1 0 1" },
  ut_dating_fight_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "0:m 8 5:m 7:m 0:m 8 7:m 0:m" },
  ut_dating_fight_p2: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "8 7:m 8 10" },
  ut_death_by_glamour_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:m 3 5:m 3:6 0:m 3 5:m 3:6" },
  ut_gasters_theme_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "7:m 8 7:m 8" },
  ut_ghouliday_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "5:^7 4:m 5:^7 4:m 5:^7 11 5:m 2:m 7:2 5 4:m 7:m" },
  ut_hopes_and_dreams_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "10:sus 0:m 1:2 3 5:m" },
  ut_megalovania_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "0:m 10 9:m 8 10 0:m 10 9:m 8 10" },
  ut_megalovania_p3: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "8 10 0:sus 8 10 0:m 11 10:^7 9:m" },
  ut_once_upon_a_time_p3: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "0 2 5 0" },
  ut_power_of_neo_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "2:m 0:2 2:m 0:2 2:m 0:2 10 0" },
  ut_quiet_water_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:m 5:2 0:m 5:2" },
  ut_room_of_dog_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "7 5" },
  ut_ruins_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "5:m 8:^7 10 3" },
  ut_song_that_might_play_when_you_fight_sans_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:m7 5:m7 0:m7 5:m7 0:m7 5:m7" },
  ut_song_that_might_play_when_you_fight_sans_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:m7 5:m7 0:m7 5:m7" },
  ut_spider_dance_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "8 0:m 8 7:sus" },
  ut_spooktune_spookwave_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "5:m 7 4:o 5 7 10 5" },
  ut_star_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0 5 0 5:m" },
  ut_star_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0 5" },
  ut_tem_shop_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "5 0 5 7 2:m" },
  ut_temmie_village_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0 5:m 0 5:m" },
  ut_undertale_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "2:m7 10:2 9:m 10:2 0" },
  ut_undertale_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "10:2 9:m 10:2 0:sus 2:m7 7:7" },
  ut_undertale_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "9:m 2:m7 7:7 10:2 0 9:m 2:m7 7:7 10:2 0 5" },
  ut_undyne_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "7:m 0 8 0:m" },
  ut_uwa_so_temperate_p1: { verdict: 'keep', page: 'undertale', at: '2026-08-24',
    judged: "3:^7 1:^7 3:^7 6" },
  ut_waterfall_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:m 10 3 0:m 10 3" },
  ut_your_best_nightmare_p1: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "0:7 9:m6 0:7 7:7 4:m6" },
  ut_your_best_nightmare_p2: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "9:m6 0:7 7:7 4:m6 0:7" },
  ut_your_best_nightmare_p3: { verdict: 'kill', page: 'undertale', at: '2026-08-24',
    judged: "2:o 0 2:o 0 8:sus 2:o 0 2:o 0 8:sus" },
};

export const KEPT = Object.keys(VERDICTS).filter((n) => VERDICTS[n].verdict === 'keep');
export const KILLED = Object.keys(VERDICTS).filter((n) => VERDICTS[n].verdict === 'kill');
