// Observed chord voicings extracted from the Unison packs in audios/ (D29).
//
// GENERATED by scripts/import-unison.mjs — do not hand-edit; re-run the importer.
// Every entry is `ratified: false` with `character: null`: an extracted corpus is
// a CANDIDATE POOL, not a library (A6.1). A character line is written when an ear
// ratifies the entry, never at import.
//
// Semitone offsets from the chord root, exactly as played on the source records.
// This is what MIDI is uniquely good for and a numeral corpus can never give
// (D28): real register, spacing and inversion. Four of the five qualities D28
// listed as missing shapes appear here — as OBSERVATIONS, not yet as library
// shapes. Promotion into src/lib/voicings.js is an ear decision.

export const VOICING_OBSERVATIONS = {
  "": [
    { offsets: [4, 16, 19, 24, 28], seen: 4, sources: ['Mat Zo & Porter Robinson - Easy (IVmaj7-I-V13sus-V11-IVmaj7-I-V13sus-iim7-vim7) .mid', 'Major Prog 06 (Isus-I-V-IV6(9)-iim7-Isus-I-V-vim7add11-IV6(9)).mid'] },
    { offsets: [0, 16, 19, 24], seen: 4, sources: ['Minor Prog 02 (i-bIImaj7-VII-i-iv-VII).mid', 'Minor Prog 01 (i-VI-iv-VII).mid'] },
    { offsets: [0, 12, 19, 24, 28], seen: 3, sources: ['Disclosure & Flume - You & Me Remix (ii-I6-vi-III-IV-I6-III) .mid', 'The Weeknd & Kendrick Lamar - Pray For Me (i-VII-iv-VI) .mid'] },
    { offsets: [0, 12, 16, 19], seen: 3, sources: ['Billie Eilish - Everything I Wanted (IVmaj7-V-iii-IVmaj7) .mid', 'Duke Dumont - Ocean Drive (i-VII-VImaj7-iv) .mid', 'Minor Prog 01 (i-v-VI-iv).mid'] },
  ],
  "-#5": [
    { offsets: [8, 24, 27, 32, 36], seen: 5, sources: ['Elton John - Rocket Man (I-IV-I-IV-I-II-IV-I-IV) .mid'] },
    { offsets: [8, 15, 20, 24, 27], seen: 3, sources: ['Elton John - Rocket Man (I-IV-I-IV-I-II-IV-I-IV) .mid'] },
    { offsets: [0, 15, 20, 24, 27], seen: 1, sources: ['Elton John - Rocket Man (I-IV-I-IV-I-II-IV-I-IV) .mid'] },
  ],
  "^7": [
    { offsets: [0, 12, 16, 19, 23], seen: 11, sources: ['Ariana Grande - Thank U, Next (VImaj7-V7-im7-III7) .mid', 'Mat Zo & Porter Robinson - Easy (IVmaj7-I-V13sus-V11-IVmaj7-I-V13sus-iim7-vim7) .mid', 'YNW Melly - Murder On My Mind (VImaj7-ivm7-i-V7-VImaj7-ivm7-i-vm7) .mid'] },
    { offsets: [0, 16, 19, 23], seen: 7, sources: ['Post Malone - Circles (Imaj7-iii-IV-iv-Imaj7-V-IVmaj7-V6) .mid', 'Billie Eilish - Everything I Wanted (IVmaj7-V-iii-IVmaj7) .mid', 'Duke Dumont - Ocean Drive (i-VII-VImaj7-iv) .mid'] },
    { offsets: [0, 19, 23, 28], seen: 4, sources: ['Minor Prog 01 (i-bIImaj7-i-bIIadd#11-bIImaj7).mid', 'Minor Prog 01 (VImaj7-v-i-v).mid', 'Minor Prog 02 (i-v-VImaj7-V).mid'] },
    { offsets: [0, 11, 16, 19], seen: 3, sources: ['Minor Prog 02 (i-isus-VImaj7#11-VImaj7).mid', 'Major Prog 04 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid', 'Major Prog 05 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid'] },
  ],
  "^7#11": [
    { offsets: [0, 11, 16, 18], seen: 6, sources: ['Minor Prog 02 (VImaj7#11-ivm7sus-i-v).mid', 'Minor Prog 02 (i-isus-VImaj7#11-VImaj7).mid', 'Major Prog 04 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid'] },
    { offsets: [0, 7, 16, 18, 23], seen: 3, sources: ['Post Malone - Circles (Imaj7-iii-IV-iv-Imaj7-V-IVmaj7-V6) .mid', 'Minor Prog 01 (bIImaj7#11-i-iim7b5-i).mid', 'Minor Prog 02 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid'] },
    { offsets: [0, 7, 11, 16, 18], seen: 1, sources: ['Minor Prog 01 (bIImaj7-i-bIImaj7#11-isus).mid'] },
    { offsets: [0, 12, 16, 18, 23], seen: 1, sources: ['Minor Prog 01 (i-VImaj7#11-ivdim7-i-iidim7-V7).mid'] },
  ],
  "^7#5": [
    { offsets: [8, 12, 16, 23], seen: 1, sources: ['Led Zeppelin - Stairway to Heaven (i-IIImaj7#5-III-IV-VImaj7-VII-i) .mid'] },
    { offsets: [8, 23, 24, 28], seen: 1, sources: ['Minor Prog 01 (imadd9-IIImaj7#5-im7-IV7-VIadd9).mid'] },
  ],
  "^9": [
    { offsets: [0, 14, 16, 19, 23], seen: 7, sources: ['Major Prog 02 (Iadd9-IVmaj7-IIadd9-iim9-Iadd9-IVmaj7-IIadd9-IVmaj9).mid', 'Major Prog 03 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Minor Prog 03 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid'] },
    { offsets: [0, 16, 19, 23, 26], seen: 6, sources: ['Minor Prog 02 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid', 'Major Prog 07 (Imaj9-bIIImaj9-bVImaj9-bIImaj9).mid', 'Major Prog 08 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
    { offsets: [0, 11, 14, 16, 19], seen: 4, sources: ['Minor Prog 02 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid', 'Minor Prog 03 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid', 'Major Prog 04 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid'] },
    { offsets: [0, 7, 11, 14, 16], seen: 2, sources: ['Major Prog 04 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid', 'Major Prog 05 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid'] },
  ],
  "11": [
    { offsets: [2, 9, 14, 17, 24], seen: 2, sources: ['The Chainsmokers & Halsey - Closer (VIadd9-VIIadd11-im7-VIIadd11) .mid'] },
    { offsets: [0, 10, 14, 17, 22], seen: 1, sources: ['Mat Zo & Porter Robinson - Easy (IVmaj7-I-V13sus-V11-IVmaj7-I-V13sus-iim7-vim7) .mid'] },
    { offsets: [5, 24, 29, 33, 34], seen: 1, sources: ['RÜFÜS DU SOL - Treat You Better (I-IVsus-vim7-Vadd11) .mid'] },
    { offsets: [9, 12, 24], seen: 1, sources: ['Tracy Chapman - Fast Car (IVmaj7-I5-vi-Vadd11) .mid'] },
  ],
  "13": [
    { offsets: [0, 10, 14, 16, 21], seen: 1, sources: ['Minor Prog 05 (vm7-im7add11-VII6-ivm9-VII9(13)-VIIadd9).mid'] },
  ],
  "13sus": [
    { offsets: [0, 10, 14, 17, 21], seen: 2, sources: ['Mat Zo & Porter Robinson - Easy (IVmaj7-I-V13sus-V11-IVmaj7-I-V13sus-iim7-vim7) .mid'] },
    { offsets: [5, 17, 21, 24], seen: 2, sources: ['Marvin Gaye - Sexual Healing (V-vim7-iii-IV-I) .mid', 'ODESZA & Madelyn Grant - Sun Models (III-v-im7) .mid'] },
    { offsets: [5, 24, 29, 33], seen: 1, sources: ['The Verve - Bitter Sweet Symphony (I-vm7-IVsus-IV) .mid'] },
    { offsets: [5, 12, 17, 21, 24, 29], seen: 1, sources: ['John Waite - Missing You (I-IVsus-Vsus) .mid'] },
  ],
  "5": [
    { offsets: [0, 7, 12], seen: 1, sources: ['Tracy Chapman - Fast Car (IVmaj7-I5-vi-Vadd11) .mid'] },
  ],
  "6": [
    { offsets: [0, 19, 24, 28, 33], seen: 2, sources: ['Disclosure & Flume - You & Me Remix (ii-I6-vi-III-IV-I6-III) .mid'] },
    { offsets: [9, 19, 24, 28], seen: 2, sources: ['Marvin Gaye - Sexual Healing (V-vim7-iii-IV-I) .mid', 'Tiësto & Post Malone - Jackie Chan (ivm7-vm7-im7-VII) .mid'] },
    { offsets: [0, 16, 19, 21, 24], seen: 2, sources: ['Major Prog 08 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Major Prog 09 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
    { offsets: [0, 12, 16, 21], seen: 1, sources: ['Post Malone - Circles (Imaj7-iii-IV-iv-Imaj7-V-IVmaj7-V6) .mid'] },
  ],
  "69": [
    { offsets: [0, 16, 19, 21, 26], seen: 1, sources: ['Minor Prog 01 (i-VII6(9)-VImaj7-vm7add11-ivm7-VImaj7-VIIadd9-V7).mid'] },
    { offsets: [0, 7, 14, 16, 21], seen: 1, sources: ['Major Prog 06 (Isus-I-V-IV6(9)-iim7-Isus-I-V-vim7add11-IV6(9)).mid'] },
    { offsets: [0, 7, 12, 16, 21], seen: 1, sources: ['Major Prog 06 (Isus-I-V-IV6(9)-iim7-Isus-I-V-vim7add11-IV6(9)).mid'] },
    { offsets: [0, 12, 14, 16, 21], seen: 1, sources: ['Minor Prog 06 (VImaj9-VII6(9)-vm7add11-im7-IIImaj7).mid'] },
  ],
  "7": [
    { offsets: [0, 12, 16, 19, 22], seen: 3, sources: ['YNW Melly - Murder On My Mind (VImaj7-ivm7-i-V7-VImaj7-ivm7-i-vm7) .mid', 'Major Prog 01 (Iadd9-III7-IVmaj7-ivm6(9)-Iadd9-III7-IVmaj7-V11-Vadd9).mid'] },
    { offsets: [4, 16, 19, 22, 24], seen: 1, sources: ['Ariana Grande - Thank U, Next (VImaj7-V7-im7-III7) .mid'] },
    { offsets: [0, 19, 22, 24, 28], seen: 1, sources: ['Ariana Grande - Thank U, Next (VImaj7-V7-im7-III7) .mid'] },
    { offsets: [0, 7, 10, 16], seen: 1, sources: ['ZHU - Faded (i-im7-i-im7-i-im7-V7) .mid'] },
  ],
  "7alt": [
    { offsets: [0, 16, 20, 22, 25], seen: 1, sources: ['Minor Prog 02 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid'] },
    { offsets: [0, 10, 13, 16, 20], seen: 1, sources: ['Minor Prog 03 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid'] },
  ],
  "7b13": [
    { offsets: [0, 22, 24, 28, 32], seen: 1, sources: ['Minor Prog 10 (im9-bIImaj9-V7-VImaj9-ivm9-bIImaj9-iim7b5-V7b13).mid'] },
  ],
  "7b5": [
    { offsets: [0, 16, 24, 30], seen: 1, sources: ['Minor Prog 01 (i-bIImaj7-i-bIIadd#11-bIImaj7).mid'] },
  ],
  "7b9": [
    { offsets: [0, 13, 16, 19, 22], seen: 1, sources: ['Minor Prog 04 (iim7b5-V7b9-im9-VImaj7-ivm9-bII9-im9).mid'] },
  ],
  "7sus": [
    { offsets: [5, 29, 34, 36, 41], seen: 1, sources: ['The Verve - Bitter Sweet Symphony (I-vm7-IVsus-IV) .mid'] },
    { offsets: [0, 10, 12, 17], seen: 1, sources: ['Minor Prog 01 (i-II7-i-II7sus).mid'] },
    { offsets: [0, 14, 19, 22], seen: 1, sources: ['Minor Prog 02 (VImaj7#11-ivm7sus-i-v).mid'] },
  ],
  "9": [
    { offsets: [0, 16, 19, 22, 26], seen: 3, sources: ['Minor Prog 04 (iim7b5-V7b9-im9-VImaj7-ivm9-bII9-im9).mid', 'Major Prog 08 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Major Prog 09 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
    { offsets: [0, 10, 14, 16, 19], seen: 1, sources: ['Major Prog 03 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
  ],
  "add9": [
    { offsets: [0, 16, 19, 24, 26], seen: 4, sources: ['Major Prog 01 (Iadd9-III7-IVmaj7-ivm6(9)-Iadd9-III7-IVmaj7-V11-Vadd9).mid', 'Major Prog 02 (Iadd9-IVmaj7-IIadd9-iim9-Iadd9-IVmaj7-IIadd9-IVmaj9).mid', 'Major Prog 10 (Iadd9-bVImaj7-bVIIadd9-IVadd9).mid'] },
    { offsets: [0, 14, 16, 19], seen: 4, sources: ['Major Prog 04 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid', 'Major Prog 05 (Iadd9-bIImaj7#11-bIIIadd9-bIImaj7-Iadd9-bIImaj7#11-bIIImaj9-bIImaj9).mid'] },
    { offsets: [0, 7, 14, 16, 19], seen: 3, sources: ['Minor Prog 05 (vm7-im7add11-VII6-ivm9-VII9(13)-VIIadd9).mid', 'Major Prog 10 (Iadd9-bVImaj7-bVIIadd9-IVadd9).mid', 'Major Prog 11 (IVmaj7sus-iim9-Iadd9-vim7add11).mid'] },
    { offsets: [0, 12, 14, 16, 19], seen: 2, sources: ['Major Prog 01 (Iadd9-III7-IVmaj7-ivm6(9)-Iadd9-III7-IVmaj7-V11-Vadd9).mid', 'Major Prog 10 (Iadd9-bVImaj7-bVIIadd9-IVadd9).mid'] },
  ],
  "m": [
    { offsets: [0, 15, 19, 24], seen: 17, sources: ['ZHU - Faded (i-im7-i-im7-i-im7-V7) .mid', 'Billie Eilish - Everything I Wanted (IVmaj7-V-iii-IVmaj7) .mid', 'Duke Dumont - Ocean Drive (i-VII-VImaj7-iv) .mid'] },
    { offsets: [0, 19, 24, 27], seen: 16, sources: ['Travis Scott - Highest In The Room (i-v) .mid', 'Minor Prog 01 (i-V-V7-i-iv-i-V7-i).mid', 'Minor Prog 02 (iv-i-iim7b5-i).mid'] },
    { offsets: [0, 12, 15, 19], seen: 14, sources: ['Lil Tecca - Ransom (i-VI-v-V) .mid', 'Duke Dumont - Ocean Drive (i-VII-VImaj7-iv) .mid', 'Minor Prog 01 (i-II7-i-II7sus).mid'] },
    { offsets: [0, 7, 12, 15, 19], seen: 5, sources: ['Disclosure & Flume - You & Me Remix (ii-I6-vi-III-IV-I6-III) .mid', 'David Bowie - Space Oddity (VI-i-VI-i-iv-VI-VII) .mid', 'Minor Prog 01 (bIImaj7-i-bIImaj7#11-isus).mid'] },
  ],
  "m11": [
    { offsets: [0, 15, 17, 19, 22], seen: 3, sources: ['Minor Prog 06 (VImaj9-VII6(9)-vm7add11-im7-IIImaj7).mid', 'Major Prog 08 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Major Prog 09 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
    { offsets: [0, 15, 22, 24, 29], seen: 2, sources: ['Minor Prog 01 (i-VII6(9)-VImaj7-vm7add11-ivm7-VImaj7-VIIadd9-V7).mid', 'Major Prog 06 (Isus-I-V-IV6(9)-iim7-Isus-I-V-vim7add11-IV6(9)).mid'] },
    { offsets: [0, 15, 17, 19, 22, 26], seen: 2, sources: ['Minor Prog 08 (im11-VImaj9-IIImaj9-ivm9-im11-VImaj9-IIImaj9-bIImaj9).mid'] },
    { offsets: [0, 7, 10, 15, 17], seen: 1, sources: ['Major Prog 03 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid'] },
  ],
  "m6": [
    { offsets: [0, 15, 21, 24], seen: 1, sources: ['Minor Prog 02 (ivm6-IIImaj7-i).mid'] },
  ],
  "m69": [
    { offsets: [0, 14, 15, 19, 21], seen: 1, sources: ['Major Prog 01 (Iadd9-III7-IVmaj7-ivm6(9)-Iadd9-III7-IVmaj7-V11-Vadd9).mid'] },
  ],
  "m7": [
    { offsets: [0, 12, 15, 19, 22], seen: 7, sources: ['YNW Melly - Murder On My Mind (VImaj7-ivm7-i-V7-VImaj7-ivm7-i-vm7) .mid', 'Major Prog 03 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Minor Prog 05 (vm7-im7add11-VII6-ivm9-VII9(13)-VIIadd9).mid'] },
    { offsets: [0, 15, 19, 22], seen: 3, sources: ['ZHU - Faded (i-im7-i-im7-i-im7-V7) .mid'] },
    { offsets: [0, 12, 19, 22, 27], seen: 2, sources: ['Daft Punk & Pharrell Williams - Get Lucky (im7-III-vm7-IV) .mid', 'Minor Prog 12 (i-vm7-IVadd9).mid'] },
    { offsets: [0, 10, 15, 19], seen: 2, sources: ['Tiësto & Post Malone - Jackie Chan (ivm7-vm7-im7-VII) .mid'] },
  ],
  "m7b5": [
    { offsets: [0, 12, 15, 18, 22], seen: 2, sources: ['Minor Prog 01 (bIImaj7#11-i-iim7b5-i).mid', 'Minor Prog 10 (im9-bIImaj9-V7-VImaj9-ivm9-bIImaj9-iim7b5-V7b13).mid'] },
    { offsets: [0, 6, 10, 15], seen: 1, sources: ['Minor Prog 02 (i-iim7b5-ivmadd9-V7).mid'] },
    { offsets: [0, 18, 22, 24], seen: 1, sources: ['Minor Prog 02 (iv-i-iim7b5-i).mid'] },
    { offsets: [0, 18, 22, 24, 27], seen: 1, sources: ['Minor Prog 04 (iim7b5-V7b9-im9-VImaj7-ivm9-bII9-im9).mid'] },
  ],
  "m9": [
    { offsets: [0, 15, 19, 22, 26], seen: 7, sources: ['Major Prog 02 (Iadd9-IVmaj7-IIadd9-iim9-Iadd9-IVmaj7-IIadd9-IVmaj9).mid', 'Major Prog 03 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Minor Prog 03 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid'] },
    { offsets: [0, 14, 15, 19, 22], seen: 3, sources: ['Minor Prog 02 (im9-VIIadd9-VImaj9-V7alt-im9-IIImaj9-VIadd9-bIImaj7#11).mid', 'Minor Prog 04 (iim7b5-V7b9-im9-VImaj7-ivm9-bII9-im9).mid'] },
    { offsets: [0, 10, 14, 15, 19], seen: 3, sources: ['Major Prog 08 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Major Prog 09 (Imaj7-IVmaj9-iim7-V9-iiim7-vim7add11-iim9-V6).mid', 'Minor Prog 10 (im9-bIImaj9-V7-VImaj9-ivm9-bIImaj9-iim7b5-V7b13).mid'] },
    { offsets: [0, 19, 22, 26, 27], seen: 1, sources: ['Minor Prog 04 (iim7b5-V7b9-im9-VImaj7-ivm9-bII9-im9).mid'] },
  ],
  "madd9": [
    { offsets: [0, 15, 19, 26], seen: 1, sources: ['Minor Prog 02 (i-iim7b5-ivmadd9-V7).mid'] },
    { offsets: [0, 12, 15, 19, 26], seen: 1, sources: ['Minor Prog 02 (i-vimadd9-i-iv).mid'] },
    { offsets: [0, 15, 19, 24, 26], seen: 1, sources: ['Minor Prog 02 (VImaj7-V-ivmadd9-i).mid'] },
    { offsets: [0, 14, 15, 19], seen: 1, sources: ['Minor Prog 01 (imadd9-IIImaj7#5-im7-IV7-VIadd9).mid'] },
  ],
  "o7": [
    { offsets: [0, 15, 18, 21, 24], seen: 1, sources: ['Minor Prog 01 (i-VImaj7#11-ivdim7-i-iidim7-V7).mid'] },
    { offsets: [0, 17, 21, 27, 30], seen: 1, sources: ['Minor Prog 01 (i-VImaj7#11-ivdim7-i-iidim7-V7).mid'] },
    { offsets: [0, 12, 18, 21], seen: 1, sources: ['Minor Prog 01 (i-iv-i-iv-iidim7).mid'] },
    { offsets: [0, 12, 15, 18, 21], seen: 1, sources: ['Minor Prog 02 (i-ivdim7-i-iidim7).mid'] },
  ],
  "sus": [
    { offsets: [5, 12, 17, 19, 24], seen: 2, sources: ['John Waite - Missing You (I-IVsus-Vsus) .mid', 'RÜFÜS DU SOL - Treat You Better (I-IVsus-vim7-Vadd11) .mid'] },
    { offsets: [0, 12, 19, 24, 26], seen: 2, sources: ['Major Prog 06 (Isus-I-V-IV6(9)-iim7-Isus-I-V-vim7add11-IV6(9)).mid'] },
    { offsets: [0, 19, 24, 28], seen: 1, sources: ['The Verve - Bitter Sweet Symphony (I-vm7-IVsus-IV) .mid'] },
    { offsets: [5, 12, 17, 22], seen: 1, sources: ['John Waite - Missing You (I-IVsus-Vsus) .mid'] },
  ],
}

/** qualities src/lib/voicings.js has no shape for, that these records DO voice */
export const FILLS_GAPS = ['5', '69', 'add9', 'madd9']
