// r34 — import Ethan's pop-pack lab judgments (audition/poplab.html export).
//
//   node scripts/import-poplab.mjs <export.json>
//
// Writes src/lib/pop-lab-labels.js (GENERATED — the lab-verdict ledger).
// Append-only across rounds like the other label files: a new export updates
// entries it names and keeps the rest. Variant marks are the experiment
// results (works/off per variant); labels are his overall reading of what the
// experiment proved. NOTHING here feeds the engine — a confirmed rule is
// promoted by hand in its own round (D95), with this ledger open beside it.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { POP_LABS } from '../src/lib/pop-labs.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/lib/pop-lab-labels.js');

const file = process.argv[2];
if (!file) { console.error('usage: node scripts/import-poplab.mjs <export.json>'); process.exit(1); }
const exp = JSON.parse(readFileSync(file, 'utf8'));
if (exp.page !== 'poplab-r34') console.warn(`  WARNING: export page is "${exp.page}", expected poplab-r34`);

let prior = {};
if (existsSync(OUT)) {
  const mod = await import(OUT);
  prior = mod.POP_LAB_LABELS ?? {};
}

const next = { ...prior };
let added = 0, updated = 0;
const unknown = [];
const ids = new Set([
  ...Object.keys(exp.verdicts ?? {}),
  ...Object.keys(exp.labels ?? {}),
  ...Object.keys(exp.variant_marks ?? {}),
  ...Object.keys(exp.variant_notes ?? {}),
]);
for (const id of ids) {
  if (!POP_LABS[id]) { unknown.push(id); continue; }
  const entry = {
    verdict: exp.verdicts?.[id] ?? prior[id]?.verdict ?? null,
    label: exp.labels?.[id] ?? prior[id]?.label ?? '',
    variantMarks: exp.variant_marks?.[id] ?? prior[id]?.variantMarks ?? {},
    variantNotes: exp.variant_notes?.[id] ?? prior[id]?.variantNotes ?? {},
    at: exp.generated ?? new Date().toISOString(),
  };
  if (prior[id]) updated++; else added++;
  next[id] = entry;
}

const header = `// GENERATED by scripts/import-poplab.mjs — Ethan's pop-pack lab verdicts.
// One entry per experiment he has judged: verdict, his overall label (what
// the experiment proved, verbatim), and per-variant works/off marks + notes.
// Addressed BY NAME only. Never edit by hand; never feed retrieval — a
// confirmed rule is promoted by hand in its own round (D95).

export const POP_LAB_LABELS = {
`;
const body = Object.entries(next)
  .map(([id, e]) => `  ${JSON.stringify(id)}: { verdict: ${JSON.stringify(e.verdict)}, label: ${JSON.stringify(e.label)},\n    variantMarks: ${JSON.stringify(e.variantMarks)}, variantNotes: ${JSON.stringify(e.variantNotes)},\n    at: ${JSON.stringify(e.at)} }`)
  .join(',\n');
writeFileSync(OUT, `${header}${body},\n};\n`);
console.log(`wrote ${OUT}`);
console.log(`  ${added} new, ${updated} updated, ${Object.keys(next).length} total`);
if (unknown.length) console.log(`  UNKNOWN ids ignored: ${unknown.join(', ')}`);
const unseen = Object.keys(POP_LABS).filter((id) => !next[id]);
if (unseen.length) console.log(`  ${unseen.length} experiments still unjudged`);
