// r33 — import Ethan's catalog labels (the audition/catalog.html export).
//
//   node scripts/import-catalog.mjs <export.json>
//
// Writes src/lib/catalog-labels.js (GENERATED — the labels ledger). Like
// verdicts.js it is append-only across rounds: a new export updates entries it
// names and keeps the rest. NOTHING here feeds retrieval automatically —
// promotion of a labeled candidate into a real library is a hand-authored,
// per-row decision (D95), made in a round with his labels open beside it.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATALOG_CANDIDATES } from '../src/lib/catalog-candidates.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/lib/catalog-labels.js');

const file = process.argv[2];
if (!file) { console.error('usage: node scripts/import-catalog.mjs <export.json>'); process.exit(1); }
const exp = JSON.parse(readFileSync(file, 'utf8'));
if (exp.page !== 'catalog-r33') console.warn(`  WARNING: export page is "${exp.page}", expected catalog-r33`);

let prior = {};
let priorPins = {};
if (existsSync(OUT)) {
  const mod = await import(OUT);
  prior = mod.CATALOG_LABELS ?? {};
  priorPins = mod.CATALOG_PAIR_PINS ?? {};
}

const next = { ...prior };
let added = 0, updated = 0, unknown = [];
const ids = new Set([
  ...Object.keys(exp.verdicts ?? {}),
  ...Object.keys(exp.labels ?? {}),
  ...Object.keys(exp.pairs ?? {}),
  ...Object.keys(exp.pair_notes ?? {}),
]);
for (const id of ids) {
  if (!CATALOG_CANDIDATES[id]) { unknown.push(id); continue; }
  const entry = {
    verdict: exp.verdicts?.[id] ?? prior[id]?.verdict ?? null,
    label: exp.labels?.[id] ?? prior[id]?.label ?? '',
    pairs: exp.pairs?.[id] ?? prior[id]?.pairs ?? [],
    // per-partner "why in / why out" — a partner id present here but absent
    // from pairs means he heard it and left it OUT for that reason
    pairNotes: exp.pair_notes?.[id] ?? prior[id]?.pairNotes ?? {},
    at: exp.generated ?? new Date().toISOString(),
  };
  if (prior[id]) updated++; else added++;
  next[id] = entry;
}

// r33/D129 keep-transition: FREEZE each newly ticked pair's {d,g,t} exactly
// as the page he judged played it. Prior pins are carried forward VERBATIM —
// a judged combo never moves because a rule or gain changed later. New ticks
// read the page build he listened to (audition/catalog.html at import time)
// through the shared client-formula module.
const pins = structuredClone(priorPins);
let pinned = 0;
try {
  const { computeLivePin } = await import('../src/lib/catalog-pins.js');
  const pageHtml = readFileSync(join(ROOT, 'audition/catalog.html'), 'utf8');
  const di = pageHtml.indexOf('const DATA = ');
  const pageData = JSON.parse(pageHtml.slice(di + 13, pageHtml.indexOf(';\n', di)));
  const byId = Object.fromEntries(pageData.candidates.map((c) => [c.id, c]));
  const pagePins = pageData.pinDelta ?? {};
  for (const [cardId, e] of Object.entries(next)) {
    const card = byId[cardId];
    if (!card || !Array.isArray(e.pairs)) continue;
    for (const pid of e.pairs) {
      if (pins[cardId]?.[pid]) continue; // already frozen — never recompute
      const p = byId[pid];
      if (!p) continue;
      pins[cardId] ??= {};
      // the page's own pin (if it carried one) IS what he heard; else the live path
      pins[cardId][pid] = pagePins[cardId]?.[pid] ? { ...pagePins[cardId][pid] } : computeLivePin(card, p);
      pinned++;
    }
  }
} catch (e) {
  console.log(`  WARNING: could not freeze new pair pins (${e.message.split('\n')[0]}) — prior pins carried forward unchanged`);
}

const L = [];
L.push('// GENERATED by scripts/import-catalog.mjs — Ethan\'s catalog labels.');
L.push('// One entry per candidate he has spoken about: verdict (good/no/unsure),');
L.push('// his label (what it contributes, verbatim), the pairings he ticked, and');
L.push('// pairNotes — his per-partner "why in / why out" words (a partner noted');
L.push('// but NOT in pairs was heard and deliberately left out).');
L.push('// Addressed BY NAME only. Never edit by hand; never feed retrieval —');
L.push('// promotion is a hand-authored decision per row (D95).');
L.push('');
L.push('export const CATALOG_LABELS = {');
for (const id of Object.keys(next).sort()) {
  const e = next[id];
  L.push(`  ${JSON.stringify(id)}: { verdict: ${JSON.stringify(e.verdict)}, label: ${JSON.stringify(e.label)},`);
  L.push(`    pairs: ${JSON.stringify(e.pairs)}, pairNotes: ${JSON.stringify(e.pairNotes ?? {})}, at: ${JSON.stringify(e.at)} },`);
}
L.push('};');
L.push('');
L.push('// ---- CATALOG_PAIR_PINS (GENERATED; carried forward by import-catalog.mjs) --');
L.push('// A ticked pair\'s {d,g,t} FROZEN at judgment time: d = semitone shift, g =');
L.push('// add-on gain multiplier, t = tempo fx. The builder uses these verbatim, so no');
L.push('// later rule or gain change can move a combo he approved (keep-transition law,');
L.push('// r33/D129). Values whose note asked for a change carry the corrected value.');
L.push(`export const CATALOG_PAIR_PINS = ${JSON.stringify(pins, null, 2)};`);
L.push('');
writeFileSync(OUT, L.join('\n'));

console.log(`wrote ${OUT}`);
console.log(`  ${added} new, ${updated} updated, ${Object.keys(next).length} total; pair pins: ${pinned} newly frozen`);
if (unknown.length) console.log(`  UNKNOWN ids (stale export?): ${unknown.join(', ')}`);
const unseen = (exp.unseen ?? []).length;
if (unseen) console.log(`  he has ${unseen} candidates still unseen — remind him the queue remembers its place`);
